name: Lint and Format

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Check if main-dev directory exists
        id: check_dir
        run: |
          if [ -d "applications/frontends/main-dev" ]; then
            echo "main-dev directory found"
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "main-dev directory not found"
            echo "exists=false" >> $GITHUB_ENV
          fi
      - name: Install dependencies
        if: env.exists == 'true'
        run: |
          cd applications/frontends/main-dev
          npm install --only=dev

      - name: Run ESLint
        if: env.exists == 'true'
        run: |
          cd applications/frontends/main-dev
          npm run lint
        continue-on-error: true

      - name: Run Prettier Check
        id: prettier_check
        if: env.exists == 'true'
        continue-on-error: true
        run: |
          # cd applications/frontends/main-dev
          # npm run prettier:check || true
          exit 1

      - name: Set Prettier Check Result
        if: env.exists == 'true'
        continue-on-error: true
        env:
          GITHUB_ENV: $GITHUB_ENV
        run: |
          cd applications/frontends/main-dev
          if npm run prettier:check; then
            echo "prettier_check_passed=true" >> $GITHUB_ENV
          else
            echo "prettier_check_passed=false" >> $GITHUB_ENV
          fi

      - name: Run Prettier Fix
        if: env.prettier_check_passed == 'false' && env.exists == 'true'
        run: |
          cd applications/frontends/main-dev
          npm run format
        continue-on-error: true

      - name: Commit changes
        if: env.prettier_check_passed == 'false' && env.exists == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd applications/frontends/main-dev
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Apply ESLint and Prettier fixes' || echo 'No changes to commit'
          git pull --rebase origin ${{ github.head_ref }} || (echo "Rebase failed due to conflicts" && exit 1)
          git push origin HEAD:${{ github.head_ref }}
