name: Lint and Format

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Check if main-dev directory exists
        id: check_dir
        run: |
          if [ -d "applications/frontends/main-dev" ]; then
            echo "main-dev directory found"
            echo "::set-output name=exists::true"
          else
            echo "main-dev directory not found"
            echo "::set-output name=exists::false"
          fi

      - name: Pull latest changes
        if: steps.check_dir.outputs.exists == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin ${{ github.head_ref }}

      - name: Install dependencies
        if: steps.check_dir.outputs.exists == 'true'
        run: |
          cd applications/frontends/main-dev
          npm install --only=dev

      - name: Run ESLint
        if: steps.check_dir.outputs.exists == 'true'
        run: |
          cd applications/frontends/main-dev
          npm run lint
        continue-on-error: true

      - name: Run Prettier Check
        id: prettier_check
        if: steps.check_dir.outputs.exists == 'true'
        run: |
          cd applications/frontends/main-dev
          npm run prettier:check

      - name: Run Prettier Fix
        if: failure() && steps.check_dir.outputs.exists == 'true'
        run: |
          cd applications/frontends/main-dev
          npm run format
        continue-on-error: true

      - name: Commit changes
        if: failure() && steps.check_dir.outputs.exists == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd applications/frontends/main-dev
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Apply ESLint and Prettier fixes' || echo 'No changes to commit'
          git pull --rebase origin ${{ github.head_ref }} || (echo "Rebase failed due to conflicts" && exit 1)
          git push origin HEAD:${{ github.head_ref }}
